version: '3.8'

services:
  go_app:
    build: .
    container_name: go_app
    ports:
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - DBURI=${DBURI}
      - SECRET=${SECRET}
      - JWT_KEY_SECRET=${JWT_KEY_SECRET}
      - EXCHANGE_API_TOKEN=${EXCHANGE_API_TOKEN}
    depends_on:
      - go_db
    networks:
      - app_network

  go_db:
    image: mysql:8.0
    container_name: go_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:    